version: "3.2"

networks:
    mynetwork:
        driver: bridge
services:
    nginx:
        hostname: nginx
        build:
            context: ./nginx
        ports:
          - 80:80
          - 443:443
        networks:
          - mynetwork
    postgres:
      image: postgres:12.0-alpine
      hostname: postgres
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
      networks:
        - mynetwork

    keycloak:
      hostname: keycloak
      image: jboss/keycloak
      ports:
        - 8080:8080
      environment:
        KEYCLOAK_USER: "admin"
        KEYCLOAK_PASSWORD: "password"
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
      networks:
        - mynetwork
      depends_on:
        - postgres

    jaeger:
        image: jaegertracing/all-in-one:1.8
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411
        ports:
        - 5775:5775/udp
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 14268:14268
        - 9411:9411
        depends_on:
        - nginx
        networks:
        - mynetwork

 
